version: '3'
services:
  nginx:
    container_name: uiapp_nginx
    restart: on-failure
    image: nginx:1.20.2
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_dir:/app/static
    ports:
      - "8000:80"
    depends_on:
      - web
  web:
    container_name: uiapp_web
    build: .
    working_dir: /app/uiapp
    tty: true
    env_file: dev.env
    ports:
      - "5000:5000"
    volumes:
     - ./uiapp:/app/uiapp
     - static_dir:/app/uiapp/static
    depends_on:
     - db
  db:
    container_name: uiapp_db
    image: postgres:14.1-alpine
    env_file: dev.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  static_dir:
  postgres_data: